services:
  mariadb:
    image: mariadb:11
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: bootguard
      MARIADB_USER: bootguard
      MARIADB_PASSWORD: bootguard
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - mariadb_data:/var/lib/mysql

  mailpit:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mariadb_data:
