server:
  port: 8443
  ssl:
    bundle: server
spring:
  application:
    name: bootguard
  ssl:
    bundle:
      pem:
        server:
          keystore:
            certificate: classpath:cert.pem
            private-key: classpath:key.pem
          truststore:
            certificate: classpath:cert.pem
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:mariadb://localhost:3306/bootguard
    username: bootguard
    password: bootguard
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  mail:
    host: ${SMTP_HOST:localhost}
    port: ${SMTP_PORT:1025}
    #    username: ${SMTP_USERNAME:}
    #    password: ${SMTP_PASSWORD:}
    properties:
      mail:
        smtp:
          #          auth: true
          starttls:
            enable: true
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
vaadin:
  launch-browser: true
bootguard:
  health-check:
    interval: 30000
    initial-delay: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
      probes:
        enabled: false
  info:
    env:
      enabled: true
    ssl:
      enabled: true
  health:
    defaults:
      enabled: false
    db:
      enabled: true
    mail:
      enabled: true
    ssl:
      enabled: true
